default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: myvod_development

test:
  <<: *default
  database: myvod_test

production:
  <<: *default
  database: myvod_production
  username: myvod
  password: <%= ENV['MYVOD_DATABASE_PASSWORD'] %>
